apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: helm-install
  namespace: tekton-will
spec:
  workspaces:
    - name: source
  params:
    - name: appName
      type: string
      description: The name of the application to be set in the Helm chart
  steps:
    - name: helm-install
      image: alpine/helm:latest
      script: |
        #!/bin/sh
        FILE_PATH="$(workspaces.source.path)/helmchart"
        helm upgrade --install $(params.appName) $FILE_PATH --history-max 1 --namespace tekton-will


