apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push-to-docker-hub
  namespace: tekton-will
spec:
  params:
    - name: IMAGE
      description: Name (reference) of the image to build.
  workspaces:
    - name: source
      description: Holds the context and Dockerfile
    - name: dockerconfig
      description: Includes a docker `config.json`
      optional: true
      mountPath: /root/.docker
  results:
    - name: IMAGE_URL
      description: URL of the image just built.
  steps:
    - name: push-image
      image: gcr.io/go-containerregistry/crane:latest
      args:
        - "push"
        - "$(workspaces.source.path)/image.tar"
        - "$(params.IMAGE)"
      securityContext:
        runAsUser: 0
    - name: write-url
      image: docker.io/library/bash:5.1.4@sha256:c523c636b722339f41b6a431b44588ab2f762c5de5ec3bd7964420ff982fb1d9
      script: |
        set -e
        image="$(params.IMAGE)"
        echo -n "${image}" | tee "$(results.IMAGE_URL.path)"