apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http01
  name: {{ .Values.pgAdminIngressName }}
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Values.pgAdminIngressHostName }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.pgAdminServiceName }}
                port:
                  number: {{ .Values.pgAdminPort }}
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.pgAdminIngressHostName }}
      secretName: {{ .Values.pgAdminAutoIngressSecretName }}