apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: williamt1997/hmbe:latest
        imagePullPolicy: Always
        ports:
          - containerPort: {{ .Values.portNumber }}
        env:
          - name: DATABASE_NAME
            valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: database-name
          - name: POSTGRES_HOST
            valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: postgres-host
          - name: POSTGRES_PORT
            valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: postgres-port
          - name: POSTGRES_USER
            valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: postgres-user
          - name: POSTGRES_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: postgres-password

---
apiVersion: {{ .Values.apiVersion }}
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: {{ .Values.serviceProtocol }}
      port: {{ .Values.portNumber }}
      targetPort: {{ .Values.portNumber }}
      nodePort: 30200