apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: {{ .Values.ingressName }}
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Values.ingressHostName }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.serviceName }}
                port:
                  number: {{ .Values.portNumber }}
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.ingressHostName }}
      secretName: {{ .Values.autoIngressSecretName }}