apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: william-persistent-volume-access
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: william-tekton-clone-git-robot
  namespace: tekton-will
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: william-tekton-eventlistener-binding
  namespace: tekton-will
subjects:
- kind: ServiceAccount
  name: william-tekton-clone-git-robot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: william-tekton-secrets-reader-binding
  namespace: homers-website-namespace
subjects:
- kind: ServiceAccount
  name: default
  namespace: tekton-will
roleRef:
  kind: Role
  name: secrets-reader
  apiGroup: rbac.authorization.k8s.io


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: william-tekton-eventlistener-clusterbinding
  namespace: tekton-will
subjects:
- kind: ServiceAccount
  name: william-tekton-clone-git-robot
  namespace: tekton-will
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: persistent-volume-access-binding
  namespace: tekton-will
subjects:
- kind: ServiceAccount
  name: default
  namespace: tekton-will
roleRef:
  kind: ClusterRole
  name: william-persistent-volume-access
  apiGroup: rbac.authorization.k8s.io
