apiVersion: v1
kind: ServiceAccount
metadata:
  name: william-tekton-clone-git-robot
  namespace: tekton-will
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tekton-will
  name: secrets-reader
rules:
- apiGroups: [""]
  resources: ["secrets", "persistentvolumeclaims", "configmaps", "services"]
  verbs: ["list", "get", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["list", "get", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["list", "get", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: william-tekton-eventlistener-binding
  namespace: tekton-will
subjects:
- kind: ServiceAccount
  name: william-tekton-clone-git-robot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: william-tekton-eventlistener-clusterbinding
  namespace: tekton-will
subjects:
- kind: ServiceAccount
  name: william-tekton-clone-git-robot
  namespace: tekton-will
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: william-tekton-secrets-reader-binding
  namespace: tekton-will
subjects:
- kind: ServiceAccount
  name: default
  namespace: tekton-will
roleRef:
  kind: Role
  name: secrets-reader
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: persistent-volume-access-binding
  namespace: tekton-will
subjects:
- kind: ServiceAccount
  name: default
  namespace: tekton-will
roleRef:
  kind: ClusterRole
  name: william-persistent-volume-access
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: william-persistent-volume-access
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["list", "get", "create", "update", "patch"]

