apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sonar-scan
  namespace: {{ .Values.namespace }}
spec:
  params:
    - name: repo-name
    - name: sonar-token-key
    - name: sonar-host
  workspaces:
    - name: source
      mountPath: /usr/src
  steps:
    - name: sonar-scanner
      image: sonarsource/sonar-scanner-cli:latest
      resources:
        requests:
          cpu:  {{ .Values.requests.highResources.cpu }}
          memory: {{ .Values.requests.highResources.memory }}
        limits:
          cpu: {{ .Values.limits.highResources.cpu }}
          memory: {{ .Values.limits.highResources.memory }}
      args:
        - "sonar-scanner"
        - "-Dsonar.projectKey=$(params.repo-name)"
        - "-Dsonar.sources=$(workspaces.source.path)"
        - "-Dsonar.host.url=$(params.sonar-host)"
        - "-Dsonar.inclusions=**/*"
      env:
        - name: SONAR_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretName }}
              key: $(params.sonar-token-key)